---
title: "Yeager - Study 1"
author: "ML"
date: "2026-02-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stargazer)
```

## 

```{r}
################################################################################
### PAPER 1 - Synergistic Mindset ----------------------------------------------
################################################################################



################################################################################
### STUDY 1 ------------------------------------------------------------------
load("data/study1.Rdata") #./paper1_synergistic_mindset/paper1_data/
study1_physio <- bcf_physio
#summary(study1_physio)
#names(study1_physio)

# MODEL 1.1. outcome: "post_stressmindset_sd" --------------------------------

# treatment is "cond" here
# (not fully clear to me how exactly they construct the outcome variable from questionnaire)
model1.1 <- lm(post_stressmindset_sd ~ cond +
                 grade + female + firstgen + factor(english) + base_testanxiety +
                 base_fixedmindset + base_stressmindset +
                 base_pss + base_expectancy, data = study1_physio
)
#summary(model1.1)
```

## Table 3 

```{r}
# add interaction terms
model1.1_interaction <- lm(post_stressmindset_sd ~ cond +
                 cond * base_stressmindset +
                 cond * base_fixedmindset +
                 cond * base_testanxiety +
                 cond * base_pss +
                 grade + female + firstgen + factor(english) + base_testanxiety +
                 base_fixedmindset + base_stressmindset +
                 base_pss + base_expectancy, data = study1_physio
               )
summary(model1.1_interaction) # cond * base_fixedmindset significant
# However: is the stressmindset really the interesting outcome here (in contrast to stress appraisal?)
```


```{r, results="asis"}
stargazer(model1.1_interaction,
         # type = "latex",
          type = "html",
          title = "Synergistic Mindset Paper - Dataset 1 - Post Stressmindset Regression",
          dep.var.labels = "post_stressmindset_sd"
          #out = "regression_summary.tex"
          )
```


